name: CI Pipeline

on:
  push:
    branches:
      - main
  pull_request:
    branches:
      - main

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v2

      - name: Set up Node.js
        uses: actions/setup-node@v2
        with:
          node-version: '14'

      - name: Install dependencies
        run: npm install

      - name: Run Hello World script
        run: node app.js

      - name: Run tests
        run: npx jest

      - name: Run regression tests
        run: |
          echo "Running regression tests..."
          npx jest

      - name: Run performance tests
        run: |
          echo "Simulating performance tests..."
          echo "Response time: 200ms, CPU usage: 20%"

      - name: Deploy to Production
        if: github.ref == 'refs/heads/main'
        run: |
          echo "Deploying to production environment..."
          # Aquí puedes agregar comandos adicionales para el despliegue real si es necesario

      - name: Monitor Production Deployment
        if: github.ref == 'refs/heads/main'
        run: |
          echo "Monitoring production deployment..."
          echo "Response time: 200ms, CPU usage: 15%, Memory usage: 250MB"
